site_name: Bleeding Heart Art Space
nav:
  - Home: index.md
  - Project Requirements: project-requirements.md
  - Software Design: software-design.md
  - Project Management: project-management.md
  - Teamwork: teamwork.md
