/*
Test for US 1.05 - Create and Manage Volunteer Schedules/Calendar

As an Admin, I want to create volunteer schedules/calendars so that shifts are organized and resources are optimized.
Acceptance Criteria: Admin can create shifts for an event.

Generated by Selenium IDE and modified after
*/

const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

describe('createShiftTest', function() {
  this.timeout(60000);
  let driver;
  let vars;

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
    vars = {};
  });

  afterEach(async function() {
    await driver.quit();
  });

  it('createShiftTest', async function() {

    // STEP 1 - CREATE A ROLE
    await driver.get("http://localhost:5173/volunteer-management")
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");
    
    await driver.findElement(By.css(".css-2mkfr1-MuiButtonBase-root-MuiButton-root")).click()
    await driver.sleep(3000);
    await driver.findElement(By.id(":r5:")).click()
    {
      const element = await driver.findElement(By.css(".css-i5v8s4-MuiInputBase-input-MuiOutlinedInput-input"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
      await driver.sleep(1000);
      await element.sendKeys("Role for createShiftTest")
    }
    await driver.sleep(1000);
    await driver.findElement(By.css(".MuiButton-textPrimary")).click()
    await driver.sleep(1000);
    await driver.wait(until.alertIsPresent(), 5000);
    const alert = await driver.switchTo().alert();
    const alertText = await alert.getText();
    assert.strictEqual(alertText, "Volunteer role created successfully!");
    await driver.sleep(1000);
    await alert.accept();
    await driver.sleep(1000);

    // STEP 2: CREATE THE EVENT TO BE USED IN SHIFT SIGNUP
    await driver.get("http://localhost:5173/calendar")
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");

    const fabButton = await driver.wait(until.elementIsVisible(driver.findElement(By.css(".MuiFab-root > .MuiSvgIcon-root"))), 10000);
    await driver.wait(until.elementIsEnabled(fabButton), 10000);
    await fabButton.click()

    await driver.wait(until.elementIsVisible(driver.findElement(By.css(".MuiDialog-root"))), 10000);
    const inputField = await driver.findElement(By.id(":r3:"));
    await driver.executeScript("arguments[0].scrollIntoView(true);", inputField);
    await inputField.click();

    const eventTitle = "Dragon House Party";
    // This part populates the fields with values
    await driver.findElement(By.id(":r3:")).sendKeys(eventTitle)
    await driver.findElement(By.id(":r5:")).click()
    await driver.findElement(By.id(":r5:")).sendKeys("999 99th Ave")
    await driver.findElement(By.id(":r7:")).click()
    await driver.findElement(By.id(":r7:")).sendKeys("11/02/2024")
    await driver.findElement(By.id(":rb:")).click()
    await driver.findElement(By.id(":rb:")).sendKeys("11/02/2024")
    await driver.findElement(By.id(":r9:")).click()
    await driver.findElement(By.id(":r9:")).clear()
    await driver.findElement(By.id(":r9:")).sendKeys("08:30")
    await driver.findElement(By.id(":r9:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.ARROW_DOWN);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.ARROW_DOWN);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.RETURN);

    await driver.findElement(By.id(":rd:")).click()
    await driver.findElement(By.id(":rd:")).click()
    await driver.findElement(By.id(":rd:")).sendKeys("15:30")

    await driver.findElement(By.id(":rf:")).click()
    {
      const element = await driver.findElement(By.css(".\\_dialogCard_hfpfo_15"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
    }
    await driver.findElement(By.id(":rf:")).sendKeys("999 99th Ave, Edmonton, AB, CA")

    // This part clicks the submit button and verifies the alert pop-up
    await driver.findElement(By.css(".css-1dj9jbk-MuiButtonBase-root-MuiButton-root")).click();
    await driver.wait(until.alertIsPresent(), 5000);
    const alert2 = await driver.switchTo().alert();
    await driver.sleep(2000);
    const alertText2 = await alert2.getText();
    await driver.sleep(2000);
    assert.strictEqual(alertText2, "Event created successfully!");
    await driver.sleep(2000);
    await alert2.accept();
    await driver.sleep(1000);

    // STEP 3: GO TO MANAGE SHIFTS
    await driver.get("http://localhost:5173/calendar");
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");
    const eventElement = await driver.findElement(By.xpath(`//div[text()="Dragon House Party"]`));
    await eventElement.click();
    await driver.sleep(3000);
    await driver.findElement(By.css(".css-1q1iyvh-MuiButtonBase-root-MuiButton-root")).click();
    await driver.sleep(2000);

    // STEP 4: CREATE AND SAVE SHIFT
    await driver.sleep(1000);
    await driver.navigate().refresh();
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");

    const dropdown = await driver.findElement(By.css(".MuiSelect-select"));
    await driver.sleep(1000);
    await driver.executeScript("arguments[0].scrollIntoView(true);", dropdown);
    await dropdown.click();
    await driver.wait(until.elementLocated(By.css('.MuiList-root .MuiMenuItem-root')), 5000);
    const options = await driver.findElements(By.css('.MuiMenuItem-root:not(.Mui-disabled)'));
    await driver.executeScript("arguments[0].scrollIntoView(true);", options[0]);
    await options[0].click();
    await driver.sleep(1000);
    await driver.findElement(By.id(":r3:")).click()
    await driver.findElement(By.id(":r3:")).sendKeys("08:40")
    await driver.sleep(1000);
    await driver.findElement(By.id(":r3:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r3:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r3:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r3:")).sendKeys(Key.ARROW_DOWN);
    await driver.findElement(By.id(":r3:")).sendKeys(Key.ARROW_DOWN);
    await driver.findElement(By.id(":r3:")).sendKeys(Key.RETURN);
    await driver.sleep(1000);
    await driver.findElement(By.id(":r5:")).click()
    await driver.findElement(By.id(":r5:")).click()
    await driver.findElement(By.id(":r5:")).sendKeys("13:40")
    await driver.sleep(1000);
    await driver.findElement(By.css(".MuiPaper-rounded")).click()
    await driver.findElement(By.css(".MuiButton-containedSecondary")).click()
    await driver.sleep(1000);
    {
      const element = await driver.findElement(By.css(".MuiButton-fullWidth"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
    }
    await driver.sleep(3000);

  });
});
