/*
Test for Volunteer Roles Feature
- This script tests the creation of volunteer roles that are assigned to specific shifts.

Generated by Selenium IDE and modified after
*/

const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

describe('createRoleTest', function() {
  this.timeout(60000);
  let driver;
  let vars;

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
    vars = {};
  });

  afterEach(async function() {
    await driver.quit();
  });

  it('createRoleTest', async function() {

    // STEP 1 - CREATE A ROLE
    await driver.get("http://localhost:5173/volunteer-management")
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");
    
    await driver.findElement(By.css(".css-2mkfr1-MuiButtonBase-root-MuiButton-root")).click()
    await driver.sleep(3000);
    await driver.findElement(By.id(":r5:")).click()
    {
      const element = await driver.findElement(By.css(".css-i5v8s4-MuiInputBase-input-MuiOutlinedInput-input"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
      await driver.sleep(1000);
      await element.sendKeys("Role Test")
    }
    await driver.sleep(1000);
    await driver.findElement(By.css(".MuiButton-textPrimary")).click()
    await driver.sleep(1000);
    await driver.wait(until.alertIsPresent(), 5000);
    const alert = await driver.switchTo().alert();
    const alertText = await alert.getText();
    assert.strictEqual(alertText, "Volunteer role created successfully!");
    await driver.sleep(1000);
    await alert.accept();
    await driver.sleep(1000);

  });
});
