/*
Test for US 1.03 - Create and Manage Events
As an Admin, I want to create and manage events so that I can schedule volunteer opportunities.
Specific Acceptance Criteria: Admin can delete an event.

Generated by Selenium IDE and modified after
*/

const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

describe('deleteEventTest', function() {
  this.timeout(60000);
  let driver;
  let vars;

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
    vars = {};
  });

  afterEach(async function() {
    await driver.quit();
  });

  it('deleteEventTest', async function() {
    // STEP 0: LOGIN
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1292, height: 684 })
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.id(":r1:")).click()
    await driver.findElement(By.id(":r1:")).sendKeys("a@test.com")
    await driver.findElement(By.id(":r3:")).click()
    await driver.findElement(By.id(":r3:")).sendKeys("atestatest")
    await driver.findElement(By.css(".css-2mkfr1-MuiButtonBase-root-MuiButton-root")).click()
    await driver.sleep(1000);
    // STEP 1: CREATE THE EVENT TO BE DELETED IN THE NEXT STEP
    await driver.get("http://localhost:5173/calendar")
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");

    const fabButton = await driver.wait(until.elementIsVisible(driver.findElement(By.css(".MuiFab-root > .MuiSvgIcon-root"))), 10000);
    await driver.wait(until.elementIsEnabled(fabButton), 10000);
    await fabButton.click()

    await driver.wait(until.elementIsVisible(driver.findElement(By.css(".MuiDialog-root"))), 10000);
    const inputField = await driver.findElement(By.id(":r3:"));
    await driver.executeScript("arguments[0].scrollIntoView(true);", inputField);
    await inputField.click();

    const eventTitle = "Event to be deleted";
    // This part populates the fields with values
    await driver.findElement(By.id(":r3:")).sendKeys(eventTitle)
    await driver.findElement(By.id(":r5:")).click()
    await driver.findElement(By.id(":r5:")).sendKeys("VVC butterdome")
    await driver.findElement(By.id(":r7:")).click()
    await driver.findElement(By.id(":r7:")).sendKeys("10/30/2024")
    await driver.findElement(By.id(":rb:")).click()
    await driver.findElement(By.id(":rb:")).sendKeys("10/30/2024")
    await driver.findElement(By.id(":r9:")).click()
    await driver.findElement(By.id(":r9:")).clear()
    await driver.findElement(By.id(":r9:")).sendKeys("08:30")
    await driver.findElement(By.id(":r9:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.ARROW_DOWN);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.ARROW_DOWN);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.RETURN);

    await driver.findElement(By.id(":rd:")).click()
    await driver.findElement(By.id(":rd:")).click()
    await driver.findElement(By.id(":rd:")).sendKeys("15:06")

    await driver.findElement(By.id(":rf:")).click()
    {
      const element = await driver.findElement(By.css(".\\_dialogCard_hfpfo_15"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
    }
    await driver.findElement(By.id(":rf:")).sendKeys("VVC, UofA, Edmonton, AB, CA")
    await driver.findElement(By.css(".css-1dj9jbk-MuiButtonBase-root-MuiButton-root")).click();

    // STEP 2: DELETE THE CREATED EVENT
    await driver.get("http://localhost:5173/calendar");
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");

    // Locates event to be deleted
    const eventElement = await driver.findElement(By.xpath(`//div[text()="${eventTitle}"]`));
    await eventElement.click();
    await driver.sleep(3000);

    // Deletes event and verifies success via an alert pop-up
    await driver.findElement(By.css(".css-13i4rnv-MuiGrid-root")).click();
    await driver.sleep(2000);
    await driver.findElement(By.css(".css-1osj8n2-MuiGrid-root")).click();
    await driver.sleep(2000);

    // This part clicks the delete confirm changes button
    const confirmButton = await driver.wait(
      until.elementIsVisible(driver.findElement(By.css(".MuiButtonBase-root:nth-child(2)"))), 
      10000
    );
    await confirmButton.click();
    await driver.sleep(2000);
  });
});
