/*
Test for Volunteer Roles Feature
- This script tests the deletion of volunteer roles that are assigned to specific shifts.

Generated by Selenium IDE and modified after
*/

const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

describe('deleteRoleTest', function() {
  this.timeout(60000);
  let driver;
  let vars;

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
    vars = {};
  });

  afterEach(async function() {
    await driver.quit();
  });

  it('deleteRoleTest', async function() {
    
    // STEP 0 - LOGIN
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1292, height: 684 })
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.id(":r1:")).click()
    await driver.findElement(By.id(":r1:")).sendKeys("a@test.com")
    await driver.findElement(By.id(":r3:")).click()
    await driver.findElement(By.id(":r3:")).sendKeys("atestatest")
    await driver.findElement(By.css(".css-2mkfr1-MuiButtonBase-root-MuiButton-root")).click()
    await driver.sleep(1000);

    // STEP 1 - CREATE A ROLE
    await driver.get("http://localhost:5173/volunteer-management")
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");
    await driver.sleep(1000);
    await driver.findElement(By.css(".MuiTab-root:nth-child(2)")).click()
    await driver.sleep(1000);
    {
      const element = await driver.findElement(By.css(".css-2mkfr1-MuiButtonBase-root-MuiButton-root"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
      await driver.sleep(1000);
    }
    {
      const element = await driver.findElement(By.css(".css-kw13he-MuiDialogContent-root"));
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
      await driver.sleep(1000);
    }
    await driver.findElement(By.id(":r37:")).click()
    await driver.findElement(By.id(":r37:")).sendKeys("Delete this role")
    await driver.findElement(By.css(".MuiButton-containedSecondary")).click()
    await driver.sleep(1000);

    // STEP 2 - DELETE THAT ROLE
    {
      const element = await driver.findElement(By.css(".MuiDataGrid-cell .PrivateSwitchBase-input"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
    }
    await driver.sleep(1000);
    {
      const element = await driver.findElement(By.css(".css-1q1iyvh-MuiButtonBase-root-MuiButton-root"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
      await driver.sleep(2000);
    }
    const confirmButton = await driver.findElement(By.xpath("//button[contains(text(), 'Confirm')]"));
    await confirmButton.click();
    await driver.sleep(2000);
  });
});
