/*
Test for US 2.04 - Sign up for Events
As a Volunteer, I want to sign up for events so that I can participate in volunteer activities.
Acceptance Criteria: Volunteers can sign up for available shifts in events.

Generated by Selenium IDE and modified after
*/

const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

describe('shiftSignupTest', function() {
  this.timeout(60000);
  let driver;
  let vars;

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
    vars = {};
  });

  afterEach(async function() {
    await driver.quit();
  });

  it('shiftSignupTest', async function() {

    // STEP 0 - LOGIN
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1292, height: 684 })
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.id(":r1:")).click()
    await driver.findElement(By.id(":r1:")).sendKeys("a@test.com")
    await driver.findElement(By.id(":r3:")).click()
    await driver.findElement(By.id(":r3:")).sendKeys("atestatest")
    await driver.findElement(By.css(".css-2mkfr1-MuiButtonBase-root-MuiButton-root")).click()
    await driver.sleep(1000);

    // STEP 1 - CREATE A ROLE
    await driver.get("http://localhost:5173/volunteer-management")
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");
    await driver.findElement(By.css(".MuiTab-root:nth-child(2)")).click()
    await driver.sleep(1000);
    {
      const element = await driver.findElement(By.css(".css-2mkfr1-MuiButtonBase-root-MuiButton-root"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
      await driver.sleep(1000);
    }
    {
      const element = await driver.findElement(By.css(".css-kw13he-MuiDialogContent-root"));
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
      await driver.sleep(1000);
    }
    await driver.findElement(By.id(":r37:")).click()
    await driver.findElement(By.id(":r37:")).sendKeys("Role for shiftSignUp")
    await driver.findElement(By.css(".MuiButton-containedSecondary")).click()
    await driver.sleep(1000);

    // STEP 2: CREATE THE EVENT TO BE USED IN SHIFT SIGNUP
    await driver.get("http://localhost:5173/calendar")
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");
    await driver.sleep(2000);
    const fabButton = await driver.wait(until.elementIsVisible(driver.findElement(By.css(".MuiFab-root > .MuiSvgIcon-root"))), 10000);
    await driver.wait(until.elementIsEnabled(fabButton), 10000);
    await fabButton.click()

    await driver.wait(until.elementIsVisible(driver.findElement(By.css(".MuiDialog-root"))), 10000);
    const inputField = await driver.findElement(By.id(":r3:"));
    await driver.executeScript("arguments[0].scrollIntoView(true);", inputField);
    await inputField.click();

    const eventTitle = "Halloween Party";
    // This part populates the fields with values
    await driver.findElement(By.id(":r3:")).sendKeys(eventTitle)
    await driver.findElement(By.id(":r5:")).click()
    await driver.findElement(By.id(":r5:")).sendKeys("CAB lounge")
    await driver.findElement(By.id(":r7:")).click()
    await driver.findElement(By.id(":r7:")).sendKeys("11/01/2024")
    await driver.findElement(By.id(":rb:")).click()
    await driver.findElement(By.id(":rb:")).sendKeys("11/01/2024")
    await driver.findElement(By.id(":r9:")).click()
    await driver.findElement(By.id(":r9:")).clear()
    await driver.findElement(By.id(":r9:")).sendKeys("08:30")
    await driver.findElement(By.id(":r9:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.TAB);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.ARROW_DOWN);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.ARROW_DOWN);
    await driver.findElement(By.id(":r9:")).sendKeys(Key.RETURN);

    await driver.findElement(By.id(":rd:")).click()
    await driver.findElement(By.id(":rd:")).click()
    await driver.findElement(By.id(":rd:")).sendKeys("15:30")

    await driver.findElement(By.id(":rf:")).click()
    {
      const element = await driver.findElement(By.css(".\\_dialogCard_hfpfo_15"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
    }
    await driver.findElement(By.id(":rf:")).sendKeys("CAB, UofA, Edmonton, AB, CA")
    await driver.findElement(By.css(".css-1dj9jbk-MuiButtonBase-root-MuiButton-root")).click();

    // STEP 3: GO TO MANAGE SHIFTS
    await driver.get("http://localhost:5173/calendar");
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");
    await driver.sleep(2000);
    const eventElement = await driver.findElement(By.xpath(`//div[text()="Halloween Party"]`));
    await eventElement.click();
    await driver.sleep(3000);
    await driver.findElement(By.css(".css-1q1iyvh-MuiButtonBase-root-MuiButton-root")).click();
    await driver.sleep(2000);

    // STEP 4: CREATE AND SAVE SHIFT
    await driver.sleep(1000);
    await driver.navigate().refresh();
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");

    const dropdown = await driver.findElement(By.css(".MuiSelect-select"));
    await driver.sleep(1000);
    await driver.executeScript("arguments[0].scrollIntoView(true);", dropdown);
    await dropdown.click();
    await driver.wait(until.elementLocated(By.css('.MuiList-root .MuiMenuItem-root')), 5000);
    const options = await driver.findElements(By.css('.MuiMenuItem-root:not(.Mui-disabled)'));
    await driver.executeScript("arguments[0].scrollIntoView(true);", options[0]);
    await options[0].click();
    await driver.sleep(1000);
    await driver.sleep(1000);
    await driver.findElement(By.css(".css-1q1iyvh-MuiButtonBase-root-MuiButton-root")).click()
    await driver.findElement(By.css(".MuiButton-containedSecondary")).click()
    await driver.sleep(1000);
    {
      const element = await driver.findElement(By.css(".MuiButton-fullWidth"))
      await driver.executeScript("arguments[0].scrollIntoView(true);", element);
      await element.click();
    }
    await driver.sleep(3000);

    // STEP 5: NAVIGATE BACK TO EVENT DETAILS PAGE
    await driver.get("http://localhost:5173/calendar");
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");
    const eventElement2 = await driver.findElement(By.xpath(`//div[text()="Halloween Party"]`));
    await eventElement2.click();
    await driver.sleep(3000);

    // STEP 6: SIGN UP FOR SHIFT
    await driver.findElement(By.css(".MuiTypography-root:nth-child(2)")).click()
    await driver.sleep(1000);
    const confirmButton = await driver.wait(
      until.elementIsVisible(driver.findElement(By.css(".MuiButtonBase-root:nth-child(2)"))), 
      10000
    );
    await confirmButton.click();
    await driver.sleep(2000);
    await driver.navigate().refresh();
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.executeScript("document.body.style.zoom='70%';");
    await driver.sleep(2000);
    const signUpText = await driver.wait(
      until.elementLocated(By.css(".css-hy1ms-MuiTypography-root")),
      10000
    );
    const textContent = await signUpText.getText();
    assert.strictEqual(textContent, "Signed up!", "The text 'Signed up!' is not displayed, sign-up may have failed.");
    await driver.sleep(1000);
  });
});
