// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('clickCalendar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('clickCalendar', async function() {
    await driver.get("http://localhost:5173/calendar")
    await driver.manage().window().setRect({ width: 1126, height: 604 })
    await driver.findElement(By.css(".rbc-month-row:nth-child(2) .rbc-day-bg:nth-child(4)")).click()
    await driver.findElement(By.id(":r1:")).click()
    await driver.findElement(By.id(":r1:")).sendKeys("test6")
    await driver.findElement(By.id(":r3:")).click()
    await driver.findElement(By.id(":r3:")).sendKeys("test6")
    await driver.findElement(By.id(":rd:")).click()
    await driver.executeScript("window.scrollTo(0,283.20001220703125)")
    await driver.findElement(By.id(":rd:")).sendKeys("test6")
    await driver.findElement(By.css(".MuiButton-containedPrimary")).click()
    assert(await driver.switchTo().alert().getText() == "Event created successfully!")
    await driver.executeScript("window.scrollTo(0,134.39999389648438)")
    await driver.findElement(By.css(".rbc-month-row:nth-child(2) .rbc-event-content")).click()
    await driver.findElement(By.css(".MuiButton-containedPrimary")).click()
    assert(await driver.switchTo().alert().getText() == "Event updated successfully!")
    await driver.executeScript("window.scrollTo(0,134.39999389648438)")
  })
})
