// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ViewCalendar', async function() {
    // Test name: ViewCalendar
    // Step # | name | target | value
    // 1 | open | http://localhost:5173/calendar | 
    await driver.get("http://localhost:5173/calendar")
    // 2 | setWindowSize | 1987x957 | 
    await driver.manage().window().setRect({ width: 1987, height: 957 })
    // 3 | click | css=.rbc-btn-group:nth-child(3) > button:nth-child(2) | 
    await driver.findElement(By.css(".rbc-btn-group:nth-child(3) > button:nth-child(2)")).click()
    // 4 | click | css=.rbc-btn-group:nth-child(3) > button:nth-child(3) | 
    await driver.findElement(By.css(".rbc-btn-group:nth-child(3) > button:nth-child(3)")).click()
    // 5 | click | css=button:nth-child(4) | 
    await driver.findElement(By.css("button:nth-child(4)")).click()
    // 6 | click | css=.rbc-btn-group:nth-child(3) > button:nth-child(1) | 
    await driver.findElement(By.css(".rbc-btn-group:nth-child(3) > button:nth-child(1)")).click()
    // 7 | click | css=.rbc-btn-group:nth-child(1) > button:nth-child(3) | 
    await driver.findElement(By.css(".rbc-btn-group:nth-child(1) > button:nth-child(3)")).click()
    // 8 | click | css=.rbc-btn-group:nth-child(1) > button:nth-child(2) | 
    await driver.findElement(By.css(".rbc-btn-group:nth-child(1) > button:nth-child(2)")).click()
    // 9 | click | css=.rbc-btn-group:nth-child(1) > button:nth-child(3) | 
    await driver.findElement(By.css(".rbc-btn-group:nth-child(1) > button:nth-child(3)")).click()
    // 10 | click | css=.rbc-btn-group:nth-child(1) > button:nth-child(3) | 
    await driver.findElement(By.css(".rbc-btn-group:nth-child(1) > button:nth-child(3)")).click()
    // 11 | doubleClick | css=.rbc-btn-group:nth-child(1) > button:nth-child(3) | 
    {
      const element = await driver.findElement(By.css(".rbc-btn-group:nth-child(1) > button:nth-child(3)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 12 | click | css=.rbc-btn-group:nth-child(1) > button:nth-child(1) | 
    await driver.findElement(By.css(".rbc-btn-group:nth-child(1) > button:nth-child(1)")).click()
    // 13 | close |  | 
    await driver.close()
  })
})
