name: Backend Tests
on:
  push:
    branches:
      - main
      - 'sprint-*'
  pull_request:
    branches:
      - main
      - 'sprint-*'

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'    # Changed to Node.js 20
    
    - name: Install and Test
      working-directory: ./backend
      run: |
        npm install
        npm run test
